# Generated by Django 5.2.17 on 2026-08-19 15:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mitglieder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mitglied",
            name="gemeinde",
            field=models.CharField(
                blank=True,
                help_text="Wohnsitz-Gemeinde — Grundlage der territorialen Zuordnung (§ 14 Abs 3).",
                max_length=120,
            ),
        ),
        migrations.CreateModel(
            name="EinmalToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zweck",
                    models.CharField(
                        choices=[
                            ("bestaetigung", "E-Mail-Bestätigung"),
                            ("login", "Login"),
                        ],
                        max_length=16,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "erstellt_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("gueltig_bis", models.DateTimeField()),
                ("verbraucht_am", models.DateTimeField(blank=True, null=True)),
                (
                    "mitglied",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Einmal-Token",
                "verbose_name_plural": "Einmal-Tokens",
            },
        ),
    ]
