# Generated by Django 5.2.17 on 2026-08-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mitglieder", "0002_mitglied_gemeinde_einmaltoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="mitglied",
            name="bundesland",
            field=models.CharField(
                blank=True,
                choices=[
                    ("burgenland", "Burgenland"),
                    ("kaernten", "Kärnten"),
                    ("niederoesterreich", "Niederösterreich"),
                    ("oberoesterreich", "Oberösterreich"),
                    ("salzburg", "Salzburg"),
                    ("steiermark", "Steiermark"),
                    ("tirol", "Tirol"),
                    ("vorarlberg", "Vorarlberg"),
                    ("wien", "Wien"),
                ],
                help_text="Wohnsitz-Bundesland — regionale Anträge sind nur in der eigenen Region möglich (F-43).",
                max_length=20,
            ),
        ),
    ]
