# Generated by Django 5.2.17 on 2026-08-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mitglieder", "0003_mitglied_bundesland"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gemeinde",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kennziffer", models.CharField(max_length=5, unique=True)),
                ("name", models.CharField(db_index=True, max_length=120)),
                ("bezirk", models.CharField(max_length=120)),
                (
                    "bundesland",
                    models.CharField(
                        choices=[
                            ("burgenland", "Burgenland"),
                            ("kaernten", "Kärnten"),
                            ("niederoesterreich", "Niederösterreich"),
                            ("oberoesterreich", "Oberösterreich"),
                            ("salzburg", "Salzburg"),
                            ("steiermark", "Steiermark"),
                            ("tirol", "Tirol"),
                            ("vorarlberg", "Vorarlberg"),
                            ("wien", "Wien"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gemeinde",
                "verbose_name_plural": "Gemeinden",
                "ordering": ["name"],
            },
        ),
    ]
