# Generated by Django 5.2.17 on 2026-08-19 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mitglieder", "0004_gemeinde"),
    ]

    operations = [
        migrations.AddField(
            model_name="mitglied",
            name="wohnsitz",
            field=models.ForeignKey(
                blank=True,
                help_text="Eindeutiger Verweis ins amtliche Gemeindeverzeichnis — Quelle für gemeinde und bundesland.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mitglieder",
                to="mitglieder.gemeinde",
            ),
        ),
    ]
