# Generated by Django 5.2.17 on 2026-08-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mitglieder", "0005_mitglied_wohnsitz"),
    ]

    operations = [
        migrations.AddField(
            model_name="mitglied",
            name="beitrag_zuletzt_am",
            field=models.DateField(
                blank=True,
                help_text="Letzter vermerkter Beitragseingang (§ 4 Abs 3) — bis zum Kontoauszug-Import händisch gepflegt.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mitglied",
            name="ist_admin",
            field=models.BooleanField(
                default=False,
                help_text="Zugang zur Mitgliederverwaltung (F-51). Ernennen und Entziehen können nur Admins; jeder Wechsel wird auditiert.",
            ),
        ),
        migrations.AddField(
            model_name="mitglied",
            name="status",
            field=models.CharField(
                choices=[
                    ("aktiv", "aktiv"),
                    ("pausiert", "pausiert (Beitrag ausständig)"),
                    ("ausgeschlossen", "ausgeschlossen"),
                ],
                default="aktiv",
                help_text="Stand der Mitgliedschaft (F-51) — jede Änderung läuft über die Verwaltung und wird auditiert.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="mitglied",
            name="status_grund",
            field=models.TextField(
                blank=True,
                help_text="Begründung des aktuellen Status (z. B. Beschlussreferenz bei Ausschluss, § 4 Abs 6).",
            ),
        ),
    ]
