# Generated by Django 5.2.17 on 2026-08-31 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mitglieder", "0006_mitglied_beitrag_zuletzt_am_mitglied_ist_admin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bankkopplung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requisition_id", models.CharField(max_length=64)),
                ("account_id", models.CharField(blank=True, max_length=64)),
                ("institution_id", models.CharField(max_length=64)),
                ("gekoppelt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "consent_bis",
                    models.DateField(
                        blank=True,
                        help_text="Ende der Bank-Zustimmung — danach in der Verwaltung neu koppeln.",
                        null=True,
                    ),
                ),
                ("zuletzt_abgerufen", models.DateTimeField(blank=True, null=True)),
                ("abruf_tag", models.DateField(blank=True, null=True)),
                ("abrufe_heute", models.PositiveSmallIntegerField(default=0)),
                ("aktiv", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Bankkopplung",
                "verbose_name_plural": "Bankkopplungen",
                "ordering": ["-gekoppelt_am"],
            },
        ),
        migrations.AlterField(
            model_name="mitglied",
            name="beitrag_zuletzt_am",
            field=models.DateField(
                blank=True,
                help_text="Letzter Beitragseingang (§ 4 Abs 3) — verbucht der Bankabgleich (F-59) oder die Verwaltung.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Beitragseingang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("betrag", models.DecimalField(decimal_places=2, max_digits=9)),
                ("gebucht_am", models.DateField()),
                ("umsatz_id", models.CharField(max_length=140, unique=True)),
                ("namens_hinweis", models.BooleanField(default=False)),
                ("erfasst_am", models.DateTimeField(auto_now_add=True)),
                (
                    "mitglied",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beitraege",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Beitragseingang",
                "verbose_name_plural": "Beitragseingänge",
                "ordering": ["-gebucht_am", "-pk"],
            },
        ),
    ]
