# Generated by Django 5.2.17 on 2026-09-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0008_mitglied_favoriten_zuerst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitglied',
            name='beitrag_zuletzt_am',
            field=models.DateField(blank=True, help_text='Letzter Beitragseingang (§ 4 Abs 3) — verbucht der Bankabgleich oder die Verwaltung.', null=True),
        ),
        migrations.AlterField(
            model_name='mitglied',
            name='bundesland',
            field=models.CharField(blank=True, choices=[('burgenland', 'Burgenland'), ('kaernten', 'Kärnten'), ('niederoesterreich', 'Niederösterreich'), ('oberoesterreich', 'Oberösterreich'), ('salzburg', 'Salzburg'), ('steiermark', 'Steiermark'), ('tirol', 'Tirol'), ('vorarlberg', 'Vorarlberg'), ('wien', 'Wien')], help_text='Wohnsitz-Bundesland — regionale Anträge sind nur in der eigenen Region möglich.', max_length=20),
        ),
        migrations.AlterField(
            model_name='mitglied',
            name='favoriten_zuerst',
            field=models.BooleanField(default=True, help_text='WeicherFilter in der Voreinstellung: ★ Favoriten zuerst. Gilt, solange kein Profil aktiv ist.'),
        ),
        migrations.AlterField(
            model_name='mitglied',
            name='ist_admin',
            field=models.BooleanField(default=False, help_text='Zugang zur Mitgliederverwaltung. Ernennen und Entziehen können nur Admins; jeder Wechsel wird auditiert.'),
        ),
        migrations.AlterField(
            model_name='mitglied',
            name='status',
            field=models.CharField(choices=[('aktiv', 'aktiv'), ('pausiert', 'pausiert (Beitrag ausständig)'), ('ausgeschlossen', 'ausgeschlossen')], default='aktiv', help_text='Stand der Mitgliedschaft — jede Änderung läuft über die Verwaltung und wird auditiert.', max_length=16),
        ),
    ]
