# Generated by Django 5.2.17 on 2026-09-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0012_adresswechsel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drosselzaehler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zweck', models.CharField(max_length=30)),
                ('kennung', models.CharField(max_length=64)),
                ('stunde', models.IntegerField(help_text='Unix-Zeit geteilt durch 3600.')),
                ('anzahl', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Drosselzähler',
                'verbose_name_plural': 'Drosselzähler',
                'constraints': [models.UniqueConstraint(fields=('zweck', 'kennung', 'stunde'), name='drossel_je_zweck_kennung_stunde')],
            },
        ),
    ]
