# Generated by Django 5.2.17 on 2026-09-12 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0013_drosselzaehler'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitglied',
            name='nebenwohnsitz',
            field=models.ForeignKey(blank=True, help_text='Zweiter Wohnsitz im amtlichen Gemeindeverzeichnis — ordnet nur zusätzlich einer Region zu, sobald die Stellgröße region-nebenwohnsitz-zaehlt auf 1 steht; am Stimmrecht ändert er nichts (§ 5 Abs 6).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nebenwohnsitz_mitglieder', to='mitglieder.gemeinde'),
        ),
        migrations.AlterField(
            model_name='mitglied',
            name='status',
            field=models.CharField(choices=[('aktiv', 'aktiv'), ('pausiert', 'pausiert (Beitrag ausständig)'), ('ausgeschlossen', 'ausgeschlossen'), ('ausgetreten', 'ausgetreten')], default='aktiv', help_text='Stand der Mitgliedschaft — jede Änderung läuft über die Verwaltung und wird auditiert.', max_length=16),
        ),
    ]
