# Generated by Django 5.2.17 on 2026-09-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0014_nebenwohnsitz_und_austritt'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitglied',
            name='freischaltung_post_am',
            field=models.DateTimeField(blank=True, help_text='Erster Versandversuch des Freischaltungsbriefs — es gibt genau einen je Konto.', null=True),
        ),
        migrations.AddField(
            model_name='mitglied',
            name='klarname_oeffentlich',
            field=models.BooleanField(default=True, help_text='Darf der Klarname öffentlich erscheinen, solange kein Anzeigename gesetzt ist (§ 5 Abs 3 lit a)? Die Registrierung fragt das ausdrücklich (Voreinstellung: nein); der Bestand ist unter dem alten Datenschutztext beigetreten, der den Anzeigenamen öffentlich nannte, und bleibt darum bei ja.'),
        ),
        migrations.AddField(
            model_name='mitglied',
            name='willkommen_post_am',
            field=models.DateTimeField(blank=True, help_text='Erster Versandversuch des Willkommensbriefs — es gibt genau einen je Konto.', null=True),
        ),
        migrations.AlterField(
            model_name='mitglied',
            name='pseudonym_oeffentlich',
            field=models.CharField(blank=True, help_text='Beständiges öffentliches Pseudonym für Anträge (§ 5 Abs 3 lit a). Leer = Klarname, sofern er öffentlich erscheinen darf, sonst „Mitglied n“.', max_length=50),
        ),
    ]
