# Generated by Django 5.2.17 on 2026-09-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0015_post_und_klarname'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitglied',
            name='ausweis_ausgestellt_am',
            field=models.DateTimeField(blank=True, help_text='Erste Ausstellung des Mitgliedsausweises; steht auf der Rückseite der Karte.', null=True),
        ),
        migrations.AddField(
            model_name='mitglied',
            name='ausweis_code',
            field=models.CharField(blank=True, default='', help_text='Prüfcode des Mitgliedsausweises (FB-K8) — einmal vergeben, damit gedruckte QR-Codes gültig bleiben.', max_length=16),
        ),
    ]
