# Generated by Django 5.2.17 on 2026-09-17 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0016_mitgliedsausweis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postauftrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(max_length=20)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('versandt_am', models.DateTimeField(blank=True, null=True)),
                ('anhang_versandt_am', models.DateTimeField(blank=True, null=True)),
                ('erledigt', models.BooleanField(default=False)),
                ('versuche', models.PositiveIntegerField(default=0)),
                ('naechster_versuch', models.DateTimeField(blank=True, null=True)),
                ('gesperrt_bis', models.DateTimeField(blank=True, null=True)),
                ('sperrcode', models.CharField(blank=True, default='', max_length=32)),
                ('mitglied', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('mitglied', 'art'), name='postauftrag_einmal')],
            },
        ),
    ]
