# Generated by Django 5.2.17 on 2026-09-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0017_postausgang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitglied',
            name='ausweis_ausgestellt_am',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt der ersten Ausstellung des einseitigen Mitgliedsausweises.', null=True),
        ),
        migrations.AlterField(
            model_name='mitglied',
            name='freischaltung_post_am',
            field=models.DateTimeField(blank=True, help_text='Freischaltungsbrief: bis 0.48 erster Versandversuch, ab 0.49 erfolgreiche Übergabe an das Mailbackend.', null=True),
        ),
        migrations.AlterField(
            model_name='mitglied',
            name='willkommen_post_am',
            field=models.DateTimeField(blank=True, help_text='Willkommensbrief: bis 0.48 erster Versandversuch, ab 0.49 erfolgreiche Übergabe an das Mailbackend.', null=True),
        ),
    ]
