# Generated by Django 5.2.17 on 2026-09-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0018_poststempel_bedeutung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mitgliedsnummernkreis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naechste', models.PositiveBigIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='mitglied',
            name='mitgliedsnummer',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mitglied',
            name='testkonto',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
