# Generated by Django 5.2.17 on 2026-09-01 17:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("verfahren", "0009_antrag_art_bewerbung_bewerbungszustimmung"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mandat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bezeichnung",
                    models.CharField(
                        help_text="Z. B. „Gemeinderat“, „Abgeordnete zum Nationalrat“.",
                        max_length=120,
                    ),
                ),
                (
                    "ebene",
                    models.CharField(
                        choices=[
                            ("bund", "Bund"),
                            ("land", "Land"),
                            ("bezirk", "Bezirk"),
                            ("gemeinde", "Gemeinde"),
                        ],
                        default="gemeinde",
                        max_length=12,
                    ),
                ),
                ("gebiet", models.CharField(blank=True, max_length=120)),
                (
                    "angetreten",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("beendet", models.DateField(blank=True, null=True)),
                ("vorstellung", models.TextField(blank=True, max_length=2000)),
                ("foto", models.BinaryField(blank=True, null=True)),
                ("foto_typ", models.CharField(blank=True, max_length=30)),
                (
                    "kandidatur",
                    models.ForeignKey(
                        blank=True,
                        help_text="Der Kandidatur-Antrag (F-70), aus dem dieses Mandat hervorging.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mandate",
                        to="verfahren.antrag",
                    ),
                ),
                (
                    "mitglied",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mandate",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mandat",
                "verbose_name_plural": "Mandate",
                "ordering": ["ebene", "gebiet", "angetreten"],
            },
        ),
        migrations.CreateModel(
            name="Aufgabe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=200)),
                ("beschreibung", models.TextField(blank=True, max_length=4000)),
                ("frist", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offen", "offen"),
                            ("laufend", "laufend"),
                            ("erledigt", "erledigt"),
                        ],
                        default="offen",
                        max_length=12,
                    ),
                ),
                (
                    "erstellt_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("aktualisiert_am", models.DateTimeField(auto_now=True)),
                (
                    "antrag",
                    models.ForeignKey(
                        blank=True,
                        help_text="Die aus der Aufgabe entstandene, vom Mandatar betreute Abstimmung.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mandats_aufgaben",
                        to="verfahren.antrag",
                    ),
                ),
                (
                    "mandat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aufgaben",
                        to="mandatare.mandat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mandats-Aufgabe",
                "verbose_name_plural": "Mandats-Aufgaben",
                "ordering": ["-aktualisiert_am"],
            },
        ),
    ]
