# Generated by Django 5.2.17 on 2026-09-04 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandatare', '0001_initial'),
        ('verfahren', '0015_hilfetexte_ohne_kennungen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandat',
            name='kandidatur',
            field=models.ForeignKey(blank=True, help_text='Der Kandidatur-Antrag, aus dem dieses Mandat hervorging.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandate', to='verfahren.antrag'),
        ),
    ]
