# Generated by Django 5.2.17 on 2026-09-12 10:35 — ergänzt um die Datenmigration der Fristen.
#
# Aufgabe.frist wird vom Kalendertag zum Zeitpunkt (Instant-Report mit Uhrzeit, Bauschritt S10).
# Djangos AlterField reicht auf SQLite (Tabelle wird neu aufgebaut, das Datum wird als Zeitpunkt
# gelesen) und auf Postgres (ALTER COLUMN … TYPE timestamptz USING frist::timestamptz) — beide
# lesen den alten Tag als Mitternacht UTC. Die Datenmigration zieht jede bestehende Frist auf
# 23:59 Wiener Zeit desselben Kalendertags: Eine Frist „bis 20.9.“ meinte den ganzen Tag.
# Idempotent (23:59 desselben Tags bleibt 23:59 desselben Tags); rückwärts geschieht nichts
# (Grundregel 7) — die Umkehrung des Feldtyps schneidet die Uhrzeit ohnehin nur ab.

from datetime import datetime, time

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.utils import timezone


def fristen_auf_tagesende(apps, schema_editor):
    Aufgabe = apps.get_model("mandatare", "Aufgabe")
    for aufgabe in Aufgabe.objects.exclude(frist=None).only("pk", "frist"):
        tag = timezone.localdate(aufgabe.frist)
        aufgabe.frist = timezone.make_aware(datetime.combine(tag, time(23, 59)))
        aufgabe.save(update_fields=["frist"])


class Migration(migrations.Migration):

    dependencies = [
        ('mandatare', '0002_hilfetexte_ohne_kennungen'),
        ('verfahren', '0020_audit_antrag_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='sitzungstag',
            field=models.BooleanField(default=False, help_text='Die Frist ist ein Sitzungstag des Vertretungskörpers — danach sind Sammelbericht (§ 7 Abs 3 lit b) und Rechenschaft (§ 7 Abs 5) fällig.'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='frist',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt der Frist (Datum und Uhrzeit, Wiener Zeit). Ein reines Datum gilt bis 23:59.', null=True),
        ),
        migrations.CreateModel(
            name='Rechenschaft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gegenstand', models.CharField(help_text='Worüber der Vertretungskörper abstimmte.', max_length=200)),
                ('sitzung_am', models.DateField()),
                ('beschluss_plattform', models.CharField(choices=[('angenommen', 'angenommen'), ('abgelehnt', 'abgelehnt'), ('keiner', 'kein Beschluss der Plattform')], default='keiner', help_text='Bei gesetztem Antrag aus dessen Phase abgeleitet und beim Speichern gesetzt.', max_length=16)),
                ('stimme', models.CharField(choices=[('dafuer', 'dafür'), ('dagegen', 'dagegen'), ('enthalten', 'enthalten'), ('nicht_teilgenommen', 'nicht teilgenommen')], max_length=20)),
                ('begruendung', models.TextField(max_length=4000)),
                ('eingetragen_am', models.DateTimeField(default=django.utils.timezone.now)),
                ('antrag', models.ForeignKey(blank=True, help_text='Der Beschluss der Plattform zu diesem Gegenstand, falls es einen gab.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechenschaft', to='verfahren.antrag')),
                ('aufgabe', models.ForeignKey(blank=True, help_text='Der angekündigte Sitzungstag, zu dem dieser Eintrag gehört.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechenschaft', to='mandatare.aufgabe')),
                ('mandat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechenschaft', to='mandatare.mandat')),
            ],
            options={
                'verbose_name': 'Rechenschaft',
                'verbose_name_plural': 'Rechenschaftsregister',
                'ordering': ['-sitzung_am', '-eingetragen_am'],
            },
        ),
        migrations.CreateModel(
            name='Bericht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(choices=[('monatsbericht', 'Monatsbericht'), ('sammelbericht', 'Sammelbericht')], max_length=16)),
                ('monat', models.DateField(blank=True, help_text='Erster Tag des berichteten Monats — beim Monatsbericht Pflicht.', null=True)),
                ('text', models.TextField(max_length=8000)),
                ('eingereicht_am', models.DateTimeField(default=django.utils.timezone.now)),
                ('aufgabe', models.ForeignKey(blank=True, help_text='Der Sitzungstag, den ein Sammelbericht abschließt — beim Sammelbericht Pflicht.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berichte', to='mandatare.aufgabe')),
                ('mandat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berichte', to='mandatare.mandat')),
            ],
            options={
                'verbose_name': 'Bericht',
                'verbose_name_plural': 'Berichte',
                'ordering': ['-eingereicht_am'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('monat__isnull', False)), fields=('mandat', 'art', 'monat'), name='bericht_monat_einmalig')],
            },
        ),
        # Zuletzt: Auf Postgres läuft die Migration in einer Transaktion — die Datenänderung
        # steht hinter allen Schemaschritten, damit kein Tabellenbau auf geänderte Zeilen folgt.
        migrations.RunPython(fristen_auf_tagesende, reverse_code=migrations.RunPython.noop),
    ]
