# Generated by Django 5.2.17 on 2026-09-15 00:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gremien', '0017_rolle_ruht_anlass_vertrauensfrage_sperre'),
        ('mandatare', '0003_instant_report_rechenschaft_berichte'),
        ('verfahren', '0022_antragsart_vertrauensfrage_rueckgabezusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandat',
            name='bestaetigt_am',
            field=models.DateField(blank=True, help_text='Bestätigung durch die Mitgliederversammlung nach einer verlorenen Vertrauensfrage (§ 7 Abs 10 lit f Z 3) — durch angenommenen Bestätigungsantrag oder Wahl in ein Organ.', null=True),
        ),
        migrations.AddField(
            model_name='mandat',
            name='mandatsvereinbarung_endet_am',
            field=models.DateField(blank=True, help_text='Ende der Mandatsvereinbarung nach § 7 Abs 10 lit f Z 5.', null=True),
        ),
        migrations.AddField(
            model_name='mandat',
            name='mandatsvereinbarung_lit_h_am',
            field=models.DateField(blank=True, help_text='Die Mandatsvereinbarung enthält § 7 Abs 3 lit h — bei Altverträgen erst nach der Ergänzung (§ 7 Abs 10 lit j). Nur dann endet sie nach einer verlorenen Vertrauensfrage.', null=True),
        ),
        migrations.AddField(
            model_name='mandat',
            name='rueckgabe_ersucht_bis',
            field=models.DateField(blank=True, help_text='Ende der 30-Tage-Frist, binnen derer die Person als ersucht gilt, das Mandat zurückzulegen (§ 7 Abs 10 lit f Z 4). Ob sie dem folgt, entscheidet sie allein.', null=True),
        ),
        migrations.AddField(
            model_name='mandat',
            name='rueckgabezusage',
            field=models.CharField(blank=True, choices=[('', 'keine Angabe'), ('abgegeben', 'abgegeben'), ('nicht_abgegeben', 'nicht abgegeben')], default='', help_text='Freiwillige, nicht einklagbare Ehrenerklärung neben der Mandatsvereinbarung (§ 7 Abs 3).', max_length=20),
        ),
        migrations.AddField(
            model_name='mandat',
            name='rueckgabezusage_am',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mandat',
            name='vertrauen_entzogen_am',
            field=models.DateTimeField(blank=True, help_text='Veröffentlichung des Ergebnisses einer verlorenen Vertrauensfrage (§ 7 Abs 10 lit e).', null=True),
        ),
        migrations.AddField(
            model_name='mandat',
            name='vertretung_beendet_am',
            field=models.DateField(blank=True, help_text='Ab hier ist die Person nicht mehr Mandatsträger der DDÖ (§ 7 Abs 10 lit f Z 8): die Rolle „Mandatar“ endet, Bereich und Register bleiben lesbar und werden fortgeführt.', null=True),
        ),
        migrations.CreateModel(
            name='Vertrauensfrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(choices=[('vertrauensfrage', 'Vertrauensfrage'), ('bestaetigung', 'Bestätigung nach § 7 Abs 10 lit f Z 3')], default='vertrauensfrage', max_length=16)),
                ('anlass_ausstaende', models.JSONField(blank=True, default=list, help_text='Ausgewiesene Ausstände als Anlass: Liste aus {kennung, art, seit, tage, bezug}.')),
                ('stimmberechtigte_partei_am_einbringungstag', models.PositiveIntegerField(default=0, help_text='Für Personenwahlen Stimmberechtigte der Partei am Tag der Einbringung (lit c).')),
                ('schwelle_partei', models.PositiveIntegerField(default=0, help_text='Fünf Prozent davon, aufgerundet — die Unterstützungsschwelle (lit c).')),
                ('schwelle_erreicht_am', models.DateTimeField(blank=True, help_text='Veröffentlichter Zeitpunkt, zu dem die Schwelle erreicht war (lit c).', null=True)),
                ('sperrhinweis', models.TextField(blank=True, help_text='Klartext der beim Einbringen erkannten Sperre nach lit g — ein Hinweis für den Integritätsrat, keine Abweisung. Leer heißt: keine Sperre erkannt.')),
                ('angefochten_am', models.DateTimeField(blank=True, help_text='Anrufung des Parteischiedsgerichts (lit h).', null=True)),
                ('aktenkennung', models.CharField(blank=True, max_length=80)),
                ('entscheidung', models.CharField(blank=True, choices=[('', 'keine'), ('aufgehoben', 'aufgehoben'), ('bestaetigt', 'bestätigt')], default='', max_length=12)),
                ('entschieden_am', models.DateTimeField(blank=True, null=True)),
                ('wirkungen_ab', models.DateTimeField(blank=True, help_text='Veröffentlichung des Ergebnisses „verloren“ — Beginn der Wirkungen (lit f).', null=True)),
                ('wirkungen_endgueltig_am', models.DateTimeField(blank=True, help_text='Ablauf der Anfechtungsfrist oder Entscheidung des Parteischiedsgerichts — das Ruhen wird zum Ende.', null=True)),
                ('verstaendigt_am', models.DateTimeField(blank=True, help_text='Erster Versandversuch der Verständigung des Mandatars (lit b).', null=True)),
                ('anlaesse', models.ManyToManyField(blank=True, help_text='Einträge des Rechenschaftsregisters, in denen das Stimmverhalten vom Beschluss abweicht.', related_name='vertrauensfragen', to='mandatare.rechenschaft')),
                ('antrag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vertrauensfrage', to='verfahren.antrag')),
                ('mandat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertrauensfragen', to='mandatare.mandat')),
                ('sperre_beschluss', models.ForeignKey(blank=True, help_text='Der Feststellungsbeschluss des Integritätsrats (lit b) — mit ihm gilt der Antrag als nicht eröffnet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vertrauensfrage_sperren', to='gremien.gremienbeschluss')),
            ],
            options={
                'verbose_name': 'Vertrauensfrage',
                'verbose_name_plural': 'Vertrauensfragen',
                'ordering': ['-antrag__eingebracht_am'],
            },
        ),
        migrations.CreateModel(
            name='Stellungnahme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4000)),
                ('erstellt_am', models.DateTimeField(default=django.utils.timezone.now)),
                ('vertrauensfrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stellungnahmen', to='mandatare.vertrauensfrage')),
            ],
            options={
                'verbose_name': 'Stellungnahme',
                'verbose_name_plural': 'Stellungnahmen',
                'ordering': ['erstellt_am', 'pk'],
            },
        ),
    ]
