# Generated by Django 5.2.17 on 2026-09-30 06:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mandatare", "0004_vertrauensfrage"),
        ("verfahren", "0026_mitgliedsbezuege_geschuetzt"),
    ]

    operations = [
        migrations.AddField(
            model_name="rechenschaft",
            name="nachgetragen_am",
            field=models.DateTimeField(
                blank=True,
                help_text="Von der Verwaltung nach dem Ende der Vertretung nachgetragen (D-L6g) — nach öffentlichen Quellen, ohne Begründung.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rechenschaft",
            name="quelle",
            field=models.CharField(
                blank=True,
                help_text="Die öffentliche Quelle eines Nachtrags der Verwaltung (D-L6g).",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="rechenschaft",
            name="begruendung",
            field=models.TextField(
                blank=True,
                help_text="Pflicht beim Eintrag des Mandatars; leer nur beim Nachtrag der Verwaltung nach dem Ende der Vertretung (§ 7 Abs 10 lit f Z 8 — „eine Begründung ist nicht mehr geschuldet“).",
                max_length=4000,
            ),
        ),
        migrations.CreateModel(
            name="FreiwilligeBegruendung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=4000)),
                (
                    "eingetragen_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "rechenschaft",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="freiwillige_begruendung",
                        to="mandatare.rechenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "freiwillige Begründung",
                "verbose_name_plural": "freiwillige Begründungen",
            },
        ),
        migrations.CreateModel(
            name="Sitzung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beginn", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ende",
                    models.DateTimeField(
                        blank=True,
                        help_text="Vom Mandatar gesetzt oder mit Ablauf der Höchstdauer (Register „live-hoechstdauer-stunden“).",
                        null=True,
                    ),
                ),
                ("ende_durch_hoechstdauer", models.BooleanField(default=False)),
                (
                    "stream",
                    models.URLField(
                        blank=True,
                        help_text="Link auf den amtlichen Stream — öffnet außerhalb der Plattform.",
                        max_length=500,
                    ),
                ),
                (
                    "aufgabe",
                    models.OneToOneField(
                        help_text="Der angekündigte Sitzungstag (FB-L2) — je Sitzungstag eine Sitzung.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sitzung",
                        to="mandatare.aufgabe",
                    ),
                ),
                (
                    "mandat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sitzungen",
                        to="mandatare.mandat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sitzung",
                "verbose_name_plural": "Sitzungen",
                "ordering": ["-beginn"],
            },
        ),
        migrations.CreateModel(
            name="Tagesordnungspunkt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nummer", models.PositiveIntegerField()),
                ("titel", models.CharField(max_length=200)),
                (
                    "erstellt_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "antrag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tagesordnungspunkte",
                        to="verfahren.antrag",
                    ),
                ),
                (
                    "sitzung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="punkte",
                        to="mandatare.sitzung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tagesordnungspunkt",
                "verbose_name_plural": "Tagesordnungspunkte",
                "ordering": ["sitzung", "nummer"],
            },
        ),
        migrations.CreateModel(
            name="Livemeldung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zeitpunkt", models.DateTimeField(default=django.utils.timezone.now)),
                ("text", models.CharField(max_length=280)),
                (
                    "stimme",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dafuer", "dafür"),
                            ("dagegen", "dagegen"),
                            ("enthalten", "enthalten"),
                            ("nicht_teilgenommen", "nicht teilgenommen"),
                        ],
                        max_length=20,
                    ),
                ),
                ("abgestimmt", models.BooleanField(default=False)),
                (
                    "berichtigt",
                    models.OneToOneField(
                        blank=True,
                        help_text="Die Meldung, die diese berichtigt — die alte bleibt stehen.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="berichtigung",
                        to="mandatare.livemeldung",
                    ),
                ),
                (
                    "sitzung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meldungen",
                        to="mandatare.sitzung",
                    ),
                ),
                (
                    "punkt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meldungen",
                        to="mandatare.tagesordnungspunkt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livemeldung",
                "verbose_name_plural": "Livemeldungen",
                "ordering": ["-zeitpunkt", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="rechenschaft",
            name="punkt",
            field=models.ForeignKey(
                blank=True,
                help_text="Der Tagesordnungspunkt des Sitzungstickers, aus dem dieser Eintrag entstand (FB-L5).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rechenschaft",
                to="mandatare.tagesordnungspunkt",
            ),
        ),
        migrations.AddConstraint(
            model_name="rechenschaft",
            constraint=models.UniqueConstraint(
                condition=models.Q(("punkt__isnull", False)),
                fields=("punkt",),
                name="rechenschaft_je_punkt",
            ),
        ),
        migrations.AddIndex(
            model_name="sitzung",
            index=models.Index(
                fields=["ende", "beginn"], name="mandatare_s_ende_171776_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tagesordnungspunkt",
            constraint=models.UniqueConstraint(
                fields=("sitzung", "nummer"), name="top_nummer_je_sitzung"
            ),
        ),
    ]
