# Generated by Django 5.2.17 on 2026-09-01 22:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("verfahren", "0010_filterprofil"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KILauf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zweck",
                    models.CharField(
                        choices=[
                            ("einschaetzung", "Einschätzung für die Gremien-Werkstatt")
                        ],
                        max_length=20,
                    ),
                ),
                ("eingabe", models.TextField()),
                ("antwort", models.TextField(blank=True)),
                ("anbieter", models.CharField(max_length=30)),
                ("modell", models.CharField(max_length=60)),
                ("tokens_ein", models.PositiveIntegerField(default=0)),
                ("tokens_aus", models.PositiveIntegerField(default=0)),
                ("dauer_ms", models.PositiveIntegerField(default=0)),
                ("erfolgreich", models.BooleanField(default=True)),
                ("fehler", models.CharField(blank=True, max_length=300)),
                (
                    "erstellt_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "angefordert_von",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "antrag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ki_laeufe",
                        to="verfahren.antrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "KI-Lauf",
                "verbose_name_plural": "KI-Läufe",
                "ordering": ["-erstellt_am"],
            },
        ),
    ]
