# Generated by Django 5.2.17 on 2026-09-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kilauf',
            name='zweck',
            field=models.CharField(choices=[('einschaetzung', 'Einschätzung für die Gremien-Werkstatt'), ('parametervorschlag', 'Vorschlag der Zukunftswerkstatt zu einem Parametertest')], max_length=20),
        ),
    ]
