# Generated by Django 5.2.17 on 2026-09-29 00:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ki", "0002_zweck_parametervorschlag"),
        ("verfahren", "0024_antragseinbettung"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="kilauf",
            name="auftrag_version",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="kilauf",
            name="zweck",
            field=models.CharField(
                choices=[
                    ("einschaetzung", "Einschätzung für die Gremien-Werkstatt"),
                    (
                        "parametervorschlag",
                        "Vorschlag der Zukunftswerkstatt zu einem Parametertest",
                    ),
                    (
                        "aehnlichkeit",
                        "Textvektoren für den Bedeutungsvergleich beim Einbringen",
                    ),
                    (
                        "rechtsbezug",
                        "Betroffene Gesetze — Vorschlag der Zukunftswerkstatt",
                    ),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="KIAuftrag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zweck",
                    models.CharField(
                        choices=[
                            ("einschaetzung", "Einschätzung für die Gremien-Werkstatt"),
                            (
                                "parametervorschlag",
                                "Vorschlag der Zukunftswerkstatt zu einem Parametertest",
                            ),
                            (
                                "aehnlichkeit",
                                "Textvektoren für den Bedeutungsvergleich beim Einbringen",
                            ),
                            (
                                "rechtsbezug",
                                "Betroffene Gesetze — Vorschlag der Zukunftswerkstatt",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                ("fassung_nummer", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("geplant", "in der Warteschlange"),
                            ("laeuft", "läuft"),
                            ("erledigt", "erledigt"),
                            ("gescheitert", "gescheitert"),
                        ],
                        default="geplant",
                        max_length=12,
                    ),
                ),
                (
                    "erstellt_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("erledigt_am", models.DateTimeField(blank=True, null=True)),
                ("versuche", models.PositiveIntegerField(default=0)),
                ("zuletzt_versucht_am", models.DateTimeField(blank=True, null=True)),
                ("naechster_versuch", models.DateTimeField(blank=True, null=True)),
                ("gesperrt_bis", models.DateTimeField(blank=True, null=True)),
                ("sperrcode", models.CharField(blank=True, default="", max_length=32)),
                ("fehler", models.CharField(blank=True, default="", max_length=300)),
                (
                    "angefordert_von",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "antrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ki_auftraege",
                        to="verfahren.antrag",
                    ),
                ),
                (
                    "lauf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auftraege",
                        to="ki.kilauf",
                    ),
                ),
            ],
            options={
                "verbose_name": "KI-Auftrag",
                "verbose_name_plural": "KI-Aufträge",
                "ordering": ["pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("zweck", "antrag", "fassung_nummer"),
                        name="kiauftrag_einmal_je_fassung",
                    )
                ],
            },
        ),
    ]
