# Generated by Django 5.2.17 on 2026-09-01 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Anstoss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=4000)),
                (
                    "seite",
                    models.CharField(
                        blank=True,
                        help_text="Pfad der Seite, von der aus der Anstoß gesendet wurde.",
                        max_length=300,
                    ),
                ),
                ("erstellt", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("neu", "neu"),
                            ("gesichtet", "gesichtet"),
                            ("erledigt", "erledigt"),
                        ],
                        default="neu",
                        max_length=12,
                    ),
                ),
                (
                    "vermerk",
                    models.CharField(
                        blank=True,
                        help_text="Interner Bearbeitungsvermerk.",
                        max_length=300,
                    ),
                ),
                (
                    "nutzer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nur gesetzt, wenn angemeldet gesendet — sonst anonym.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anstoesse",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Anstoß",
                "verbose_name_plural": "Anstöße",
                "ordering": ["-erstellt"],
            },
        ),
    ]
