# Generated by Django 5.2.17 on 2026-08-19 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("verfahren", "0006_kategorie_eltern_alter_antrag_kategorien"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagesZahl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField(unique=True)),
                ("aufrufe", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Tageszahl",
                "verbose_name_plural": "Tageszahlen",
                "ordering": ["datum"],
            },
        ),
        migrations.CreateModel(
            name="TagesBesucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField(db_index=True)),
                ("kennung", models.CharField(max_length=16)),
            ],
            options={
                "verbose_name": "Tagesbesucher-Kennung",
                "verbose_name_plural": "Tagesbesucher-Kennungen",
                "unique_together": {("datum", "kennung")},
            },
        ),
        migrations.CreateModel(
            name="AntragAufruf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField()),
                ("aufrufe", models.PositiveIntegerField(default=0)),
                (
                    "antrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aufrufe",
                        to="verfahren.antrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antragsaufruf",
                "verbose_name_plural": "Antragsaufrufe",
                "unique_together": {("antrag", "datum")},
            },
        ),
    ]
