# Generated by Django 5.2.17 on 2026-08-19 14:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEintrag",
            fields=[
                ("lfd", models.BigAutoField(primary_key=True, serialize=False)),
                ("zeit", models.DateTimeField(default=django.utils.timezone.now)),
                ("ereignis", models.JSONField()),
                ("hash", models.CharField(editable=False, max_length=64)),
            ],
            options={
                "verbose_name": "Audit-Eintrag",
                "verbose_name_plural": "Audit-Log",
                "ordering": ["lfd"],
            },
        ),
        migrations.CreateModel(
            name="Antrag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=200)),
                (
                    "eingebracht_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("unterstuetzung", "unterstuetzung"),
                            ("beratung", "beratung"),
                            ("abstimmung", "abstimmung"),
                            ("angenommen", "angenommen"),
                            ("abgelehnt", "abgelehnt"),
                            ("verfallen", "verfallen"),
                            ("zurueckgewiesen", "zurueckgewiesen"),
                            ("zurueckgezogen", "zurueckgezogen"),
                        ],
                        default="unterstuetzung",
                        max_length=20,
                    ),
                ),
                (
                    "phase_beginn",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "policy_snapshot",
                    models.JSONField(
                        help_text="Unveränderliche Kopie der Policy zum Einbringungszeitpunkt (§ 5 Abs 5)."
                    ),
                ),
                (
                    "stimmberechtigte_anzahl",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Zahl der Stimmberechtigten, festgestellt und veröffentlicht bei Abstimmungsbeginn (§ 4 Abs 4 lit a).",
                        null=True,
                    ),
                ),
                (
                    "zurueckweisung_begruendung",
                    models.TextField(
                        blank=True,
                        help_text="Nur bei formaler Zurückweisung durch den Integritätsrat — wird veröffentlicht (§ 5 Abs 2).",
                    ),
                ),
                (
                    "eingebracht_von",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="antraege",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Antrag",
                "verbose_name_plural": "Anträge",
                "ordering": ["-eingebracht_am"],
            },
        ),
        migrations.CreateModel(
            name="Verfahrensordnung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_id", models.SlugField(max_length=60)),
                ("version", models.PositiveIntegerField()),
                (
                    "regeln",
                    models.JSONField(
                        help_text="Serialisierte Policy — validiert gegen plattform_core.Policy."
                    ),
                ),
                ("beschlossen_am", models.DateTimeField(blank=True, null=True)),
                ("aktiv", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Verfahrensordnung",
                "verbose_name_plural": "Verfahrensordnungen",
                "unique_together": {("policy_id", "version")},
            },
        ),
        migrations.CreateModel(
            name="AntragsFassung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nummer", models.PositiveIntegerField()),
                ("wortlaut", models.TextField()),
                ("begruendung", models.TextField(blank=True)),
                (
                    "erstellt_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "antrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fassungen",
                        to="verfahren.antrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antragsfassung",
                "verbose_name_plural": "Antragsfassungen",
                "unique_together": {("antrag", "nummer")},
            },
        ),
        migrations.CreateModel(
            name="Stimmabgabe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pseudonym", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "stimme",
                    models.CharField(
                        choices=[
                            ("ja", "ja"),
                            ("nein", "nein"),
                            ("enthaltung", "enthaltung"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "abgegeben_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "antrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stimmabgaben",
                        to="verfahren.antrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stimmabgabe",
                "verbose_name_plural": "Stimmabgaben",
                "unique_together": {("antrag", "pseudonym")},
            },
        ),
        migrations.CreateModel(
            name="StimmRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pseudonym", models.UUIDField()),
                (
                    "pruefcode",
                    models.CharField(default="", editable=False, max_length=32),
                ),
                (
                    "antrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stimmregister",
                        to="verfahren.antrag",
                    ),
                ),
                (
                    "mitglied",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stimmregister-Eintrag (geschützt)",
                "verbose_name_plural": "Stimmregister (geschützt)",
                "unique_together": {("antrag", "mitglied")},
            },
        ),
        migrations.CreateModel(
            name="Unterstuetzung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "erklaert_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "antrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unterstuetzungen",
                        to="verfahren.antrag",
                    ),
                ),
                (
                    "mitglied",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Unterstützung",
                "verbose_name_plural": "Unterstützungen",
                "unique_together": {("antrag", "mitglied")},
            },
        ),
    ]
