# Generated by Django 5.2.17 on 2026-08-19 16:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verfahren", "0002_kommentar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="antrag",
            name="ebene",
            field=models.CharField(
                choices=[
                    ("bund", "Bund"),
                    ("land", "Land"),
                    ("bezirk", "Bezirk"),
                    ("gemeinde", "Gemeinde"),
                ],
                default="bund",
                help_text="Territoriale Ebene (§ 14) — regionale Anträge erscheinen im Bereich c des Hauptfensters (F-43).",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="antrag",
            name="gebiet",
            field=models.CharField(
                blank=True,
                help_text="Name des Landes, Bezirks bzw. der Gemeinde bei regionalen Anträgen.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="antrag",
            name="hervorgehoben",
            field=models.BooleanField(
                default=False,
                help_text="Bereich b des Hauptfensters (F-42): wichtige Abstimmung, die alle angeht, aber wenig Aufmerksamkeit bekommt — oder bei der Beeinflussungsrisiko besteht. Entscheidung des Integritätsrats, nie eines Algorithmus.",
            ),
        ),
        migrations.AddField(
            model_name="antrag",
            name="hervorhebung_begruendung",
            field=models.TextField(
                blank=True,
                help_text="Öffentliche Begründung der Hervorhebung — Transparenz ist Bedingung (§ 2 Abs 5).",
            ),
        ),
        migrations.CreateModel(
            name="Favorit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "erstellt_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "antrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoriten",
                        to="verfahren.antrag",
                    ),
                ),
                (
                    "mitglied",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoriten",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorit",
                "verbose_name_plural": "Favoriten",
                "unique_together": {("antrag", "mitglied")},
            },
        ),
    ]
