# Generated by Django 5.2.17 on 2026-08-19 17:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verfahren", "0003_antrag_ebene_antrag_gebiet_antrag_hervorgehoben_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("beschreibung", models.CharField(blank=True, max_length=300)),
                (
                    "eurovoc",
                    models.CharField(
                        blank=True,
                        help_text="Zugeordnete EuroVoc-Domänen (Ebene 2, für Feinverschlagwortung und RIS/EUR-Lex-Anschluss).",
                        max_length=300,
                    ),
                ),
                ("reihenfolge", models.PositiveIntegerField(default=0)),
                ("aktiv", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Kategorie",
                "verbose_name_plural": "Kategorien",
                "ordering": ["reihenfolge", "slug"],
            },
        ),
        migrations.AddField(
            model_name="antrag",
            name="kategorien",
            field=models.ManyToManyField(
                blank=True,
                help_text="Lebensbereiche des Antrags (F-45). Wählt der Mensch; eine KI schlägt später vor (F-47).",
                related_name="antraege",
                to="verfahren.kategorie",
            ),
        ),
        migrations.CreateModel(
            name="KategorieAbo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "erstellt_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "kategorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abos",
                        to="verfahren.kategorie",
                    ),
                ),
                (
                    "mitglied",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kategorie_abos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategorie-Abo",
                "verbose_name_plural": "Kategorie-Abos",
                "unique_together": {("kategorie", "mitglied")},
            },
        ),
    ]
