# Generated by Django 5.2.17 on 2026-08-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verfahren", "0004_kategorie_antrag_kategorien_kategorieabo"),
    ]

    operations = [
        migrations.AddField(
            model_name="kategorie",
            name="schlagworte",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Schlagwortliste für die automatische Zuordnung (F-47, Stufe 1) — gepflegt in der YAML-Quelle.",
            ),
        ),
    ]
