# Generated by Django 5.2.17 on 2026-08-19 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verfahren", "0005_kategorie_schlagworte"),
    ]

    operations = [
        migrations.AddField(
            model_name="kategorie",
            name="eltern",
            field=models.ForeignKey(
                blank=True,
                help_text="Übergeordnete Kategorie — leer bei Hauptkategorien. Der Baum trägt die Drill-down-Zuordnung (F-45).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="kinder",
                to="verfahren.kategorie",
            ),
        ),
        migrations.AlterField(
            model_name="antrag",
            name="kategorien",
            field=models.ManyToManyField(
                blank=True,
                help_text="Lebensbereiche des Antrags (F-45) — automatisch zugeordnet (F-47), durch den Integritätsrat korrigierbar.",
                related_name="antraege",
                to="verfahren.kategorie",
            ),
        ),
    ]
