# Generated by Django 5.2.17 on 2026-08-20 03:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verfahren", "0006_kategorie_eltern_alter_antrag_kategorien"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vollzugseintrag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offen", "offen"),
                            ("in_umsetzung", "in Umsetzung"),
                            ("blockiert", "blockiert"),
                            ("umgesetzt", "umgesetzt"),
                            ("zurueckgestellt", "zurückgestellt"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "vermerk",
                    models.TextField(
                        blank=True,
                        help_text="Öffentlicher Vermerk: Stand, Hindernis, nächster Schritt, Termin (F-56-Raster).",
                        max_length=2000,
                    ),
                ),
                (
                    "erstellt_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "antrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vollzug",
                        to="verfahren.antrag",
                    ),
                ),
                (
                    "durch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vollzugseintrag",
                "verbose_name_plural": "Umsetzungsregister",
                "ordering": ["-erstellt_am", "-pk"],
            },
        ),
    ]
