# Generated by Django 5.2.17 on 2026-09-01 17:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verfahren", "0008_ordnung_v2_fristen"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="antrag",
            name="art",
            field=models.CharField(
                choices=[("sache", "Sachantrag"), ("mandat", "Mandats-Kandidatur")],
                default="sache",
                help_text="Sachantrag (§ 5) oder Mandats-Kandidatur (§ 7 Abs 1, F-70).",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="Bewerbung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vorstellung",
                    models.TextField(
                        blank=True,
                        help_text="Wer bin ich, wofür stehe ich — öffentlich sichtbar.",
                        max_length=2000,
                    ),
                ),
                (
                    "erstellt_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("zurueckgezogen", models.BooleanField(default=False)),
                (
                    "antrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bewerbungen",
                        to="verfahren.antrag",
                    ),
                ),
                (
                    "mitglied",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bewerbungen",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bewerbung",
                "verbose_name_plural": "Bewerbungen",
                "ordering": ["erstellt_am", "pk"],
                "unique_together": {("antrag", "mitglied")},
            },
        ),
        migrations.CreateModel(
            name="BewerbungsZustimmung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pseudonym", models.UUIDField()),
                (
                    "abgegeben_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "bewerbung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zustimmungen",
                        to="verfahren.bewerbung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bewerbungs-Zustimmung",
                "verbose_name_plural": "Bewerbungs-Zustimmungen",
                "unique_together": {("bewerbung", "pseudonym")},
            },
        ),
    ]
