# Generated by Django 5.2.17 on 2026-09-01 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verfahren", "0009_antrag_art_bewerbung_bewerbungszustimmung"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FilterProfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                (
                    "regler",
                    models.JSONField(
                        default=dict,
                        help_text="Reglerstellungen 0–100 je Regel (plattform_core.weicherfilter).",
                    ),
                ),
                ("aktiv", models.BooleanField(default=False)),
                ("geaendert_am", models.DateTimeField(auto_now=True)),
                (
                    "mitglied",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filterprofile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "WeicherFilter-Profil",
                "verbose_name_plural": "WeicherFilter-Profile",
                "ordering": ["pk"],
                "unique_together": {("mitglied", "name")},
            },
        ),
    ]
