# Generated by Django 5.2.17 on 2026-09-04 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verfahren', '0013_chatsystem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kommentar',
            name='bezug_absatz',
            field=models.PositiveIntegerField(blank=True, help_text='Absatz des Vorschlags, auf den sich die Kritik bezieht (ab 1).', null=True),
        ),
        migrations.AddField(
            model_name='kommentar',
            name='ist_kritik',
            field=models.BooleanField(default=False, help_text='Konkrete Kritik am Vorschlag des Expertenrats — geht bei Rückgabe an ihn (FB-G6).'),
        ),
        migrations.AddField(
            model_name='kommentar',
            name='system',
            field=models.BooleanField(default=False, help_text='Von der Plattform angelegt — der „Passt alles“-Eintrag des Abstimmungs-Chats (FB-G6).'),
        ),
        migrations.AlterField(
            model_name='kommentar',
            name='mitglied',
            field=models.ForeignKey(blank=True, help_text='Leer beim Systembeitrag der Plattform („Passt alles“, FB-G6) — sonst der Verfasser.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
