# Generated by Django 5.2.17 on 2026-09-04 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verfahren', '0014_abstimmungschat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='antrag',
            name='art',
            field=models.CharField(choices=[('sache', 'Sachantrag'), ('mandat', 'Mandats-Kandidatur')], default='sache', help_text='Sachantrag (§ 5) oder Mandats-Kandidatur (§ 7 Abs 1).', max_length=12),
        ),
        migrations.AlterField(
            model_name='antrag',
            name='ebene',
            field=models.CharField(choices=[('bund', 'Bund'), ('land', 'Land'), ('bezirk', 'Bezirk'), ('gemeinde', 'Gemeinde')], default='bund', help_text='Territoriale Ebene (§ 14) — regionale Anträge erscheinen im Bereich c des Hauptfensters.', max_length=12),
        ),
        migrations.AlterField(
            model_name='antrag',
            name='hervorgehoben',
            field=models.BooleanField(default=False, help_text='Bereich b des Hauptfensters: wichtige Abstimmung, die alle angeht, aber wenig Aufmerksamkeit bekommt — oder bei der Beeinflussungsrisiko besteht. Entscheidung des Integritätsrats, nie eines Algorithmus.'),
        ),
        migrations.AlterField(
            model_name='antrag',
            name='kategorien',
            field=models.ManyToManyField(blank=True, help_text='Lebensbereiche des Antrags — automatisch zugeordnet, durch den Integritätsrat korrigierbar.', related_name='antraege', to='verfahren.kategorie'),
        ),
        migrations.AlterField(
            model_name='filterprofil',
            name='favoriten_zuerst',
            field=models.BooleanField(default=True, help_text='★ Favoriten zuerst: Anträge aus abonnierten Lebensbereichen stehen vorn.'),
        ),
        migrations.AlterField(
            model_name='kategorie',
            name='eltern',
            field=models.ForeignKey(blank=True, help_text='Übergeordnete Kategorie — leer bei Hauptkategorien. Der Baum trägt die Drill-down-Zuordnung.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kinder', to='verfahren.kategorie'),
        ),
        migrations.AlterField(
            model_name='kategorie',
            name='schlagworte',
            field=models.JSONField(blank=True, default=list, help_text='Schlagwortliste für die automatische Zuordnung — gepflegt in der YAML-Quelle.'),
        ),
        migrations.AlterField(
            model_name='kommentar',
            name='archiviert_am',
            field=models.DateTimeField(blank=True, help_text='Bei Hochstufung gesetzt: der Beitrag wandert ins Archiv.', null=True),
        ),
        migrations.AlterField(
            model_name='kommentar',
            name='ist_kritik',
            field=models.BooleanField(default=False, help_text='Konkrete Kritik am Vorschlag des Expertenrats — geht bei Rückgabe an ihn.'),
        ),
        migrations.AlterField(
            model_name='kommentar',
            name='mitglied',
            field=models.ForeignKey(blank=True, help_text='Leer beim Systembeitrag der Plattform („Passt alles“) — sonst der Verfasser.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kommentar',
            name='system',
            field=models.BooleanField(default=False, help_text='Von der Plattform angelegt — der „Passt alles“-Eintrag des Abstimmungs-Chats.'),
        ),
        migrations.AlterField(
            model_name='vollzugseintrag',
            name='vermerk',
            field=models.TextField(blank=True, help_text='Öffentlicher Vermerk: Stand, Hindernis, nächster Schritt, Termin.', max_length=2000),
        ),
    ]
