# Generated by Django 5.2.17 on 2026-09-11 18:54

import django.db.models.fields.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verfahren', '0019_antrag_indizes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditeintrag',
            index=models.Index(django.db.models.fields.json.KeyTransform('antrag', 'ereignis'), name='audit_antrag_idx'),
        ),
    ]
