# Generated by Django 5.2.17 on 2026-09-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verfahren', '0020_audit_antrag_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antrag',
            name='art',
            field=models.CharField(choices=[('sache', 'Sachantrag'), ('mandat', 'Mandats-Kandidatur'), ('mandatsfrage', 'Mandatsfrage')], default='sache', help_text='Sachantrag (§ 5), Mandats-Kandidatur (§ 7 Abs 1) oder Mandatsfrage eines Mandatars (§ 7 Abs 9).', max_length=12),
        ),
    ]
