# Generated by Django 5.2.17 on 2026-09-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verfahren', '0021_antragsart_mandatsfrage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bewerbung',
            name='rueckgabezusage',
            field=models.CharField(blank=True, choices=[('', 'keine Angabe'), ('abgegeben', 'abgegeben'), ('nicht_abgegeben', 'nicht abgegeben')], default='', help_text='Erklärung nach § 7 Abs 3, ob die Rückgabezusage abgegeben wird — mit der Bewerbung abgegeben, beim Kandidatur-Antrag ausgewiesen; leer bei Bewerbungen aus der Zeit vor 0.48.', max_length=20),
        ),
        migrations.AlterField(
            model_name='antrag',
            name='art',
            field=models.CharField(choices=[('sache', 'Sachantrag'), ('mandat', 'Mandats-Kandidatur'), ('mandatsfrage', 'Mandatsfrage'), ('vertrauensfrage', 'Vertrauensfrage')], default='sache', help_text='Sachantrag (§ 5), Mandats-Kandidatur (§ 7 Abs 1), Mandatsfrage eines Mandatars (§ 7 Abs 9) oder Vertrauensfrage zu einem Mandatsträger (§ 7 Abs 10).', max_length=20),
        ),
    ]
