# Generated by Django 5.2.17 on 2026-09-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verfahren", "0022_antragsart_vertrauensfrage_rueckgabezusage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hintergrundlauf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                ("gesperrt_bis", models.DateTimeField(blank=True, null=True)),
                ("sperrcode", models.CharField(blank=True, default="", max_length=32)),
                ("zuletzt_begonnen", models.DateTimeField(blank=True, null=True)),
                ("zuletzt_beendet", models.DateTimeField(blank=True, null=True)),
                ("zuletzt_stand", models.JSONField(blank=True, default=dict)),
                ("fehler", models.CharField(blank=True, default="", max_length=300)),
            ],
            options={
                "verbose_name": "Hintergrundlauf",
                "verbose_name_plural": "Hintergrundläufe",
            },
        ),
    ]
