# Generated by Django 5.2.17 on 2026-09-29 00:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verfahren", "0023_hintergrundlauf"),
    ]

    operations = [
        migrations.CreateModel(
            name="AntragsEinbettung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fassung_nummer", models.PositiveIntegerField()),
                ("modell", models.CharField(max_length=60)),
                ("vektor", models.JSONField()),
                (
                    "erstellt_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "antrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="einbettungen",
                        to="verfahren.antrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antragseinbettung",
                "verbose_name_plural": "Antragseinbettungen",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("antrag", "fassung_nummer", "modell"),
                        name="antragseinbettung_einmal_je_fassung_und_modell",
                    )
                ],
            },
        ),
    ]
