# Generated by Django 5.2.17 on 2026-09-29 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verfahren", "0024_antragseinbettung"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reaktion",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="reaktion",
            name="zurueckgenommen_am",
            field=models.DateTimeField(
                blank=True,
                help_text="Gesetzt, wenn die Reaktion zurückgenommen oder gewechselt wurde — die Zeile bleibt (Grundregel 7), gezählt wird sie nicht mehr.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="reaktion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("zurueckgenommen_am__isnull", True)),
                fields=("kommentar", "mitglied"),
                name="reaktion_eine_aktive_je_mitglied",
            ),
        ),
    ]
