# Generated by Django 5.2.17 on 2026-09-30 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mandatare", "0005_sitzungsmodus"),
        ("verfahren", "0026_mitgliedsbezuege_geschuetzt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="kommentar",
            name="beantwortet_am",
            field=models.DateTimeField(
                blank=True,
                help_text="Im Chat einer Sitzung: vom Mandatar als beantwortet markiert (FB-L5) — nicht zurücknehmbar.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kommentar",
            name="sitzung",
            field=models.ForeignKey(
                blank=True,
                help_text="Der Chat einer Sitzung im Sitzungsmodus (FB-L5) — dann ohne Antrag.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="beitraege",
                to="mandatare.sitzung",
            ),
        ),
        migrations.AddField(
            model_name="lesestand",
            name="sitzung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesestaende",
                to="mandatare.sitzung",
            ),
        ),
        migrations.AlterField(
            model_name="kommentar",
            name="antrag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kommentare",
                to="verfahren.antrag",
            ),
        ),
        migrations.AlterField(
            model_name="lesestand",
            name="antrag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesestaende",
                to="verfahren.antrag",
            ),
        ),
        migrations.AddIndex(
            model_name="kommentar",
            index=models.Index(
                fields=["sitzung", "erstellt_am"], name="verfahren_k_sitzung_b74707_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="kommentar",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("antrag__isnull", False), ("sitzung__isnull", True)),
                    models.Q(("antrag__isnull", True), ("sitzung__isnull", False)),
                    _connector="OR",
                ),
                name="kommentar_genau_ein_bezug",
            ),
        ),
        migrations.AddConstraint(
            model_name="lesestand",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sitzung__isnull", False)),
                fields=("mitglied", "sitzung"),
                name="lesestand_je_sitzung",
            ),
        ),
        migrations.AddConstraint(
            model_name="lesestand",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("antrag__isnull", False), ("sitzung__isnull", True)),
                    models.Q(("antrag__isnull", True), ("sitzung__isnull", False)),
                    _connector="OR",
                ),
                name="lesestand_genau_ein_bezug",
            ),
        ),
    ]
