# Generated by Django 5.2.17 on 2026-09-01 22:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schluessel", models.SlugField(max_length=60, unique=True)),
                ("wert", models.CharField(max_length=100)),
                ("einheit", models.CharField(blank=True, max_length=30)),
                ("beschreibung", models.TextField(max_length=1000)),
                (
                    "quelle",
                    models.CharField(
                        help_text="Satzungs-/Konzeptstelle, z. B. „§ 5 Abs 12“.",
                        max_length=200,
                    ),
                ),
                (
                    "geaendert_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Parameter",
                "verbose_name_plural": "Parameterregister",
                "ordering": ["schluessel"],
            },
        ),
    ]
