# Generated by Django 5.2.17 on 2026-09-04 18:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0002_parameter_schema_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ['gruppe', 'schluessel'], 'verbose_name': 'Parameter', 'verbose_name_plural': 'Parameterregister'},
        ),
        migrations.AddField(
            model_name='parameter',
            name='gruppe',
            field=models.CharField(choices=[('verfahren', 'Verfahren'), ('gremien', 'Gremien'), ('weicherfilter', 'WeicherFilter'), ('faecher', 'Fächer'), ('ki', 'Zukunftswerkstatt'), ('schutz', 'Schutz'), ('kacheln', 'Kacheln')], default='verfahren', help_text='Ordnet den Eintrag auf der Registerseite ein (FB-J2).', max_length=20),
        ),
        migrations.AddField(
            model_name='parameter',
            name='status',
            field=models.CharField(choices=[('gueltig', 'gültig'), ('im_test', 'im Test'), ('vorgeschlagen', 'vorgeschlagen')], default='gueltig', help_text='Ein Wert „im Test“ gilt nur für neu beginnende Verfahren (§ 5 Abs 5).', max_length=16),
        ),
        migrations.AddField(
            model_name='parameter',
            name='test_bis',
            field=models.DateField(blank=True, help_text='Ende eines laufenden Tests — danach fällt der Wert zurück.', null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='test_hypothese',
            field=models.CharField(blank=True, help_text='Was der Test zeigen soll — steht öffentlich am Band.', max_length=300),
        ),
        migrations.CreateModel(
            name='Aenderung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alter_wert', models.CharField(max_length=100)),
                ('neuer_wert', models.CharField(max_length=100)),
                ('grund', models.TextField(max_length=1000)),
                ('geaendert_am', models.DateTimeField(default=django.utils.timezone.now)),
                ('durch', models.CharField(blank=True, help_text='Wer die Änderung veranlasst hat — Rolle oder Organ, nie eine Person.', max_length=80)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historie', to='parameter.parameter')),
            ],
            options={
                'verbose_name': 'Änderung',
                'verbose_name_plural': 'Änderungen',
                'ordering': ['-geaendert_am'],
            },
        ),
    ]
