# Generated by Django 5.2.17 on 2026-09-09 06:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gremien', '0011_koordinationsrat_werkstatt'),
        ('ki', '0002_zweck_parametervorschlag'),
        ('parameter', '0003_register_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testwert', models.CharField(max_length=100)),
                ('alter_wert', models.CharField(blank=True, help_text='Der Wert vor dem Test — der Rückweg führt hierher.', max_length=100)),
                ('hypothese', models.CharField(help_text='Was der Test zeigen soll — steht öffentlich am Band.', max_length=300)),
                ('messgroesse', models.CharField(help_text='Kennung aus /kennzahlen.json, an der der Erfolg gemessen wird.', max_length=80)),
                ('beginn', models.DateField(blank=True, null=True)),
                ('ende', models.DateField(help_text='Danach fällt der Wert von selbst zurück.')),
                ('rueckweg', models.TextField(help_text='Wie der alte Wert zurückkommt, wenn es schiefgeht.', max_length=1000)),
                ('status', models.CharField(choices=[('geplant', 'geplant — Beschluss steht aus'), ('laeuft', 'läuft'), ('ausgewertet', 'ausgewertet'), ('eingefuehrt', 'eingeführt'), ('verworfen', 'verworfen')], default='geplant', max_length=16)),
                ('werte_vorher', models.JSONField(blank=True, default=dict, help_text='Kennzahlen-Schnappschuss zu Beginn.')),
                ('werte_nachher', models.JSONField(blank=True, default=dict, help_text='Kennzahlen-Schnappschuss am Ende.')),
                ('auswertung', models.TextField(blank=True, max_length=4000)),
                ('angelegt_am', models.DateTimeField(default=django.utils.timezone.now)),
                ('ausgewertet_am', models.DateTimeField(blank=True, null=True)),
                ('angeordnet_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('beschluss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametertests', to='gremien.gremienbeschluss')),
                ('einfuehrung_beschluss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='einfuehrungen', to='gremien.gremienbeschluss')),
                ('ki_lauf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parametertests', to='ki.kilauf')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='parameter.parameter')),
            ],
            options={
                'verbose_name': 'Parametertest',
                'verbose_name_plural': 'Parametertests',
                'ordering': ['-angelegt_am'],
            },
        ),
    ]
