# Generated by Django 5.2.17 on 2026-09-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0004_parametertest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='status',
            field=models.CharField(choices=[('gueltig', 'gültig'), ('im_test', 'im Test'), ('vorgeschlagen', 'vorgeschlagen')], default='gueltig', help_text='Ein Wert „im Test“ gilt bei Werten der Verfahrensordnung nur für neu beginnende Verfahren (§ 5 Abs 5); alle anderen Stellgrößen wirken sofort.', max_length=16),
        ),
    ]
