# Generated by Django 5.2.17 on 2026-09-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0005_status_hilfetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='gruppe',
            field=models.CharField(choices=[('verfahren', 'Verfahren'), ('gremien', 'Gremien'), ('weicherfilter', 'WeicherFilter'), ('faecher', 'Fächer'), ('ki', 'Zukunftswerkstatt'), ('schutz', 'Schutz'), ('kacheln', 'Kacheln'), ('mandatare', 'Mandatare')], default='verfahren', help_text='Ordnet den Eintrag auf der Registerseite ein (FB-J2).', max_length=20),
        ),
    ]
