# Generated by Django 5.2.17 on 2026-09-01 22:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("verfahren", "0010_filterprofil"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entwurf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_arbeit", "in Arbeit (Expertenrat)"),
                            ("pruefung", "in Prüfung (Gruppe 2)"),
                            ("unterstuetzer", "liegt den Unterstützern vor"),
                            ("angenommen", "zur Endabstimmung übergeben"),
                        ],
                        default="in_arbeit",
                        max_length=16,
                    ),
                ),
                ("runde", models.PositiveIntegerField(default=1)),
                (
                    "vollzugsbezug",
                    models.BooleanField(
                        default=False,
                        help_text="Unmittelbarer Vollzugs- oder Beschaffungsbezug — dann prüft Gruppe 2 (§ 6 Abs 7).",
                    ),
                ),
                ("eingereicht_am", models.DateTimeField(blank=True, null=True)),
                ("review_frist", models.DateTimeField(blank=True, null=True)),
                ("ueberarbeitung_frist", models.DateTimeField(blank=True, null=True)),
                (
                    "erstellt_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "antrag",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entwurf",
                        to="verfahren.antrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entwurf",
                "verbose_name_plural": "Entwürfe",
            },
        ),
        migrations.CreateModel(
            name="EntwurfsBeitrag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=4000)),
                (
                    "erstellt_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "entwurf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beitraege",
                        to="gremien.entwurf",
                    ),
                ),
                (
                    "mitglied",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["erstellt_am"],
            },
        ),
        migrations.CreateModel(
            name="Pruefung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("runde", models.PositiveIntegerField()),
                (
                    "ergebnis",
                    models.CharField(
                        choices=[
                            ("validiert", "validiert"),
                            ("zurueck", "mit Begründung zurückgegeben"),
                            ("austausch", "Austausch bei Gruppe 1 beantragt"),
                        ],
                        max_length=12,
                    ),
                ),
                ("begruendung", models.TextField(max_length=4000)),
                (
                    "erstellt_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "korat_entscheid",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stattgegeben", "stattgegeben"),
                            ("abgelehnt", "abgelehnt"),
                        ],
                        help_text="Nur bei Austauschanträgen: die Entscheidung des Koordinationsrats.",
                        max_length=12,
                    ),
                ),
                ("korat_begruendung", models.TextField(blank=True, max_length=2000)),
                (
                    "durch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entwurf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pruefungen",
                        to="gremien.entwurf",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prüfung (Gruppe 2)",
                "verbose_name_plural": "Prüfungen (Gruppe 2)",
                "ordering": ["-erstellt_am"],
            },
        ),
        migrations.CreateModel(
            name="Rolle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gremium",
                    models.CharField(
                        choices=[
                            ("expertenrat1", "Expertenrat — Gruppe 1 (Entwurf)"),
                            ("expertenrat2", "Expertenrat — Gruppe 2 (Prüfung)"),
                            ("koordinationsrat", "Koordinationsrat"),
                            ("integritaetsrat", "Integritätsrat"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "berufen_am",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "endet_am",
                    models.DateField(
                        help_text="Automatisches Erlöschen — Rollen sind Rollen auf Zeit (§ 6 Abs 8)."
                    ),
                ),
                (
                    "bestaetigt",
                    models.BooleanField(
                        default=False,
                        help_text="Bestätigung der Bestellung durch die Mitgliederversammlung (§ 6 Abs 8).",
                    ),
                ),
                ("beendet_grund", models.CharField(blank=True, max_length=200)),
                (
                    "mitglied",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rollen",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rolle",
                "verbose_name_plural": "Rollen",
                "ordering": ["gremium", "berufen_am"],
            },
        ),
        migrations.CreateModel(
            name="EinreichStimme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("runde", models.PositiveIntegerField()),
                ("einverstanden", models.BooleanField()),
                (
                    "abgegeben_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "mitglied",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entwurf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="einreich_stimmen",
                        to="gremien.entwurf",
                    ),
                ),
            ],
            options={
                "unique_together": {("entwurf", "mitglied", "runde")},
            },
        ),
        migrations.CreateModel(
            name="EntwurfsFassung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nummer", models.PositiveIntegerField()),
                ("wortlaut", models.TextField()),
                ("begruendung", models.TextField(blank=True)),
                (
                    "erstellt_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "entwurf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fassungen",
                        to="gremien.entwurf",
                    ),
                ),
                (
                    "verfasst_von",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entwurfsfassung",
                "verbose_name_plural": "Entwurfsfassungen",
                "ordering": ["nummer"],
                "unique_together": {("entwurf", "nummer")},
            },
        ),
        migrations.CreateModel(
            name="UnterstuetzerVotum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("runde", models.PositiveIntegerField()),
                ("annehmen", models.BooleanField()),
                ("wunsch", models.TextField(blank=True, max_length=2000)),
                (
                    "abgegeben_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "entwurf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unterstuetzer_voten",
                        to="gremien.entwurf",
                    ),
                ),
                (
                    "mitglied",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["abgegeben_am"],
                "unique_together": {("entwurf", "mitglied", "runde")},
            },
        ),
    ]
