# Generated by Django 5.2.17 on 2026-09-01 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gremien", "0001_initial"),
        ("ki", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entwurfsbeitrag",
            name="ki_lauf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="beitraege",
                to="ki.kilauf",
            ),
        ),
    ]
