# Generated by Django 5.2.17 on 2026-09-04 22:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gremien', '0003_voten_in_den_abstimmungschat'),
        ('verfahren', '0015_hilfetexte_ohne_kennungen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GremienBeschluss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gremium', models.CharField(choices=[('expertenrat1', 'Expertenrat — Gruppe 1 (Entwurf)'), ('expertenrat2', 'Expertenrat — Gruppe 2 (Prüfung)'), ('koordinationsrat', 'Koordinationsrat'), ('integritaetsrat', 'Integritätsrat')], max_length=20)),
                ('gegenstand', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True, max_length=4000)),
                ('optionen', models.JSONField(help_text='Liste aus {„wert“, „name“} — „wert“ zählt die Regel, „name“ liest der Mensch.')),
                ('frist', models.DateTimeField(blank=True, help_text='Danach wird mit den vorliegenden Stimmen ausgewertet.', null=True)),
                ('status', models.CharField(choices=[('offen', 'offen'), ('entschieden', 'entschieden'), ('ohne_ergebnis', 'ohne Ergebnis (Frist abgelaufen)')], default='offen', max_length=16)),
                ('ergebnis', models.CharField(blank=True, max_length=40)),
                ('regel_version', models.PositiveIntegerField(default=0, help_text='Fassung der Auszählregel, mit der entschieden wurde.')),
                ('umsetzungsvermerk', models.TextField(blank=True, help_text='Was wie umgesetzt wird — nach der Entscheidung.', max_length=2000)),
                ('angelegt_am', models.DateTimeField(default=django.utils.timezone.now)),
                ('entschieden_am', models.DateTimeField(blank=True, null=True)),
                ('angelegt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='angelegte_beschluesse', to=settings.AUTH_USER_MODEL)),
                ('antrag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gremienbeschluesse', to='verfahren.antrag')),
                ('entwurf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beschluesse', to='gremien.entwurf')),
            ],
            options={
                'verbose_name': 'Gremienbeschluss',
                'verbose_name_plural': 'Gremienbeschlüsse',
                'ordering': ['-angelegt_am'],
            },
        ),
        migrations.CreateModel(
            name='GremienStimme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=40)),
                ('begruendung', models.TextField(blank=True, max_length=4000)),
                ('abgegeben_am', models.DateTimeField(default=django.utils.timezone.now)),
                ('geaendert_am', models.DateTimeField(blank=True, null=True)),
                ('beschluss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stimmen', to='gremien.gremienbeschluss')),
                ('mitglied', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stimme im Gremium',
                'verbose_name_plural': 'Stimmen im Gremium',
                'ordering': ['abgegeben_am'],
                'unique_together': {('beschluss', 'mitglied')},
            },
        ),
    ]
