# Generated by Django 5.2.17 on 2026-09-04 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gremien', '0004_interne_beschluesse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pruefung',
            name='beschluss',
            field=models.OneToOneField(blank=True, help_text='Die interne Abstimmung, aus der dieses Urteil hervorging (§ 6 Abs 2 lit e).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruefung', to='gremien.gremienbeschluss'),
        ),
        migrations.AlterField(
            model_name='pruefung',
            name='durch',
            field=models.ForeignKey(blank=True, help_text='Leer, wenn das Gremium gemeinsam entschieden hat — dann steht alles am Beschluss.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
