# Generated by Django 5.2.17 on 2026-09-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gremien', '0006_beschluss_anlass_nummer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gremienbeschluss',
            name='zustand_vorher',
            field=models.JSONField(blank=True, help_text='Was der Beschluss überschrieben hat — damit eine Aufhebung den alten Stand wiederherstellen kann, statt ihn zu erraten (§ 5 Abs 2: die Zurückweisung ist beim Parteischiedsgericht bekämpfbar).', null=True),
        ),
        migrations.AlterField(
            model_name='gremienbeschluss',
            name='anlass',
            field=models.CharField(choices=[('intern', 'innere Angelegenheit des Rates'), ('pruefung', 'Prüfung eines Vorschlags (§ 6 Abs 7)'), ('hervorhebung', 'Hervorhebung eines Antrags (§ 5 Abs 10 lit b)'), ('hervorhebung_aufheben', 'Hervorhebung aufheben (§ 5 Abs 10 lit b)'), ('zurueckweisung', 'Zurückweisung eines Antrags (§ 5 Abs 2)'), ('zurueckweisung_aufheben', 'Zurückweisung aufheben (§ 5 Abs 2)')], default='intern', help_text='Wozu der Beschluss gefasst wird; die Wirkungstabelle verzweigt hierüber.', max_length=30),
        ),
    ]
