# Generated by Django 5.2.17 on 2026-09-08 15:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gremien', '0007_integritaetsrat'),
        ('verfahren', '0015_hilfetexte_ohne_kennungen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gremienbeschluss',
            name='anlass',
            field=models.CharField(choices=[('intern', 'innere Angelegenheit des Rates'), ('pruefung', 'Prüfung eines Vorschlags (§ 6 Abs 7)'), ('hervorhebung', 'Hervorhebung eines Antrags (§ 5 Abs 10 lit b)'), ('hervorhebung_aufheben', 'Hervorhebung aufheben (§ 5 Abs 10 lit b)'), ('zurueckweisung', 'Zurückweisung eines Antrags (§ 5 Abs 2)'), ('zurueckweisung_aufheben', 'Zurückweisung aufheben (§ 5 Abs 2)'), ('aussetzung', 'Abstimmung oder Vollzug aussetzen (§ 6 Abs 3 lit d)'), ('aussetzung_aufheben', 'Aussetzung aufheben (§ 6 Abs 3 lit d)'), ('regelpruefung', 'Jährliche Prüfung der automatisierten Regeln (§ 2 Abs 6)')], default='intern', help_text='Wozu der Beschluss gefasst wird; die Wirkungstabelle verzweigt hierüber.', max_length=30),
        ),
        migrations.CreateModel(
            name='Aussetzung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gegenstand', models.CharField(choices=[('abstimmung', 'laufende Abstimmung'), ('vollzug', 'Vollzug eines Beschlusses')], max_length=12)),
                ('begruendung', models.TextField(help_text='Zu begründen und zu veröffentlichen.', max_length=4000)),
                ('beginn', models.DateTimeField(default=django.utils.timezone.now)),
                ('schiedsgericht_am', models.DateTimeField(blank=True, help_text='Wann der Antrag an das Parteischiedsgericht gestellt wurde.', null=True)),
                ('schiedsgericht_kennung', models.CharField(blank=True, max_length=60)),
                ('beendet_am', models.DateTimeField(blank=True, null=True)),
                ('beendet_grund', models.CharField(blank=True, max_length=300)),
                ('antrag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aussetzungen', to='verfahren.antrag')),
                ('beschluss', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='aussetzung', to='gremien.gremienbeschluss')),
            ],
            options={
                'verbose_name': 'Aussetzung',
                'verbose_name_plural': 'Aussetzungen',
                'ordering': ['-beginn'],
            },
        ),
        migrations.CreateModel(
            name='Regelpruefung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jahr', models.PositiveIntegerField()),
                ('stand', models.JSONField(help_text='Das Regelverzeichnis, wie es bei der Prüfung stand.')),
                ('verzeichnis_fassung', models.PositiveIntegerField(default=0)),
                ('ergebnis', models.CharField(blank=True, choices=[('geprueft', 'geprüft, keine Beanstandung'), ('beanstandet', 'beanstandet')], max_length=12)),
                ('vermerk', models.TextField(blank=True, max_length=4000)),
                ('geprueft_am', models.DateTimeField(blank=True, null=True)),
                ('beschluss', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='regelpruefung', to='gremien.gremienbeschluss')),
            ],
            options={
                'verbose_name': 'Regelprüfung',
                'verbose_name_plural': 'Regelprüfungen',
                'ordering': ['-jahr', '-pk'],
            },
        ),
    ]
