# Generated by Django 5.2.17 on 2026-09-08 18:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gremien', '0008_aussetzung_regelpruefung'),
        ('verfahren', '0015_hilfetexte_ohne_kennungen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fachliste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schluessel', models.CharField(help_text='Pseudonyme Kennung für die Auslosung — stabil, auch nach einem Widerruf.', max_length=16, unique=True)),
                ('interessenbindungen', models.TextField(blank=True, help_text='Offenzulegen (§ 6 Abs 7). Leer heißt „keine“ — und wird auch so angezeigt.', max_length=4000)),
                ('honorare', models.TextField(blank=True, help_text='Entgeltliche Nebentätigkeiten und Zuwendungen — die Satzung nennt sie neben den Interessenbindungen ausdrücklich (§ 6 Abs 7).', max_length=4000)),
                ('seit', models.DateField(default=django.utils.timezone.localdate)),
                ('gestrichen_am', models.DateField(blank=True, null=True)),
                ('gestrichen_grund', models.CharField(blank=True, max_length=200)),
                ('einwilligung_widerrufen_am', models.DateField(blank=True, help_text='§ 8 Abs 4: Die Einwilligung ist jederzeit widerrufbar; danach steht hier der Schlüssel statt des Namens. Der sachliche Inhalt bleibt erhalten.', null=True)),
                ('fachgebiete', models.ManyToManyField(help_text='Lebensbereiche, für die diese Person zur Verfügung steht (§ 6 Abs 7).', related_name='fachleute', to='verfahren.kategorie')),
                ('mitglied', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fachlisteneintrag', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fachlisten-Eintrag',
                'verbose_name_plural': 'Fachliste',
                'ordering': ['schluessel'],
            },
        ),
    ]
