# Generated by Django 5.2.17 on 2026-09-08 18:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gremien', '0009_fachliste'),
        ('verfahren', '0015_hilfetexte_ohne_kennungen'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolle',
            name='antrag',
            field=models.ForeignKey(blank=True, help_text='Gesetzt, wenn die Rolle für einen einzelnen Antrag gelost wurde (§ 6 Abs 7). Leer heißt parteiweit — so waren alle Rollen vor der Auslosung.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gremienrollen', to='verfahren.antrag'),
        ),
        migrations.CreateModel(
            name='Auslosung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runde', models.PositiveIntegerField(default=1)),
                ('anker_lfd', models.BigIntegerField(help_text='Laufende Nummer des Audit-Eintrags, der den Zufall gab.')),
                ('anker', models.CharField(help_text='Sein Hash — der Anker der Ziehung.', max_length=64)),
                ('regel_fassung', models.PositiveIntegerField()),
                ('groessen', models.JSONField()),
                ('lostopf', models.JSONField()),
                ('ausgeschlossen', models.JSONField(default=list)),
                ('plaetze', models.JSONField(default=list)),
                ('gezogen_am', models.DateTimeField(default=django.utils.timezone.now)),
                ('antrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auslosungen', to='verfahren.antrag')),
            ],
            options={
                'verbose_name': 'Auslosung',
                'verbose_name_plural': 'Auslosungen',
                'ordering': ['antrag', 'runde'],
                'unique_together': {('antrag', 'runde')},
            },
        ),
        migrations.AddField(
            model_name='rolle',
            name='auslosung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollen', to='gremien.auslosung'),
        ),
    ]
