# Generated by Django 5.2.17 on 2026-09-09 06:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gremien', '0010_auslosung'),
        ('verfahren', '0015_hilfetexte_ohne_kennungen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interessenbindung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runde', models.PositiveIntegerField(default=1)),
                ('text', models.CharField(max_length=1000)),
                ('erklaert_am', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Interessenbindung',
                'verbose_name_plural': 'Interessenbindungen',
                'ordering': ['erklaert_am'],
            },
        ),
        migrations.CreateModel(
            name='Ueberlastungsmeldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stelle', models.CharField(help_text='Wer meldet — Organ, Gliederung oder Mandat, nie eine Person.', max_length=120)),
                ('begruendung', models.TextField(max_length=4000)),
                ('gemeldet_am', models.DateTimeField(default=django.utils.timezone.now)),
                ('vorschlag', models.TextField(blank=True, max_length=4000)),
                ('erledigt_am', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Überlastungsmeldung',
                'verbose_name_plural': 'Überlastungsmeldungen',
                'ordering': ['-gemeldet_am'],
            },
        ),
        migrations.CreateModel(
            name='WunschVermerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fassung', models.PositiveIntegerField(help_text='In welcher Fassung der Wunsch berücksichtigt wurde.')),
                ('vermerkt_am', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='entwurfsbeitrag',
            name='absatz',
            field=models.PositiveIntegerField(blank=True, help_text='Gesetzt, wenn der Beitrag an einen Absatz der aktuellen Fassung gebunden ist (FB-I2).', null=True),
        ),
        migrations.AddField(
            model_name='gremienbeschluss',
            name='umsetzung_durch',
            field=models.ForeignKey(blank=True, help_text='Wer die Umsetzung übernimmt — ein Mitglied des Rates.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zugewiesene_umsetzungen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gremienbeschluss',
            name='umsetzung_frist',
            field=models.DateField(blank=True, help_text='Bis wann.', null=True),
        ),
        migrations.AddField(
            model_name='pruefung',
            name='korat_beschluss',
            field=models.ForeignKey(blank=True, help_text='Der Beschluss des Koordinationsrats über den Austauschantrag (§ 6 Abs 7).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruefungen_austausch', to='gremien.gremienbeschluss'),
        ),
        migrations.AlterField(
            model_name='gremienbeschluss',
            name='anlass',
            field=models.CharField(choices=[('intern', 'innere Angelegenheit des Rates'), ('pruefung', 'Prüfung eines Vorschlags (§ 6 Abs 7)'), ('hervorhebung', 'Hervorhebung eines Antrags (§ 5 Abs 10 lit b)'), ('hervorhebung_aufheben', 'Hervorhebung aufheben (§ 5 Abs 10 lit b)'), ('zurueckweisung', 'Zurückweisung eines Antrags (§ 5 Abs 2)'), ('zurueckweisung_aufheben', 'Zurückweisung aufheben (§ 5 Abs 2)'), ('aussetzung', 'Abstimmung oder Vollzug aussetzen (§ 6 Abs 3 lit d)'), ('aussetzung_aufheben', 'Aussetzung aufheben (§ 6 Abs 3 lit d)'), ('regelpruefung', 'Jährliche Prüfung der automatisierten Regeln (§ 2 Abs 6)'), ('einreichung', 'Einreichung eines Vorschlags (§ 5 Abs 12)'), ('austausch', 'Austausch der Gruppe 1 (§ 6 Abs 7)'), ('hervorhebung_anregen', 'Hervorhebung beim Integritätsrat beantragen (§ 5 Abs 10 lit b)'), ('ueberlastung', 'Vorschlag zu einer Überlastungsmeldung (§ 6 Abs 10)'), ('parametertest', 'Test eines Registerwerts anordnen (§ 6 Abs 11 lit c)'), ('parameter_einfuehrung', 'Einführung eines Registerwerts (§ 6 Abs 11 lit c)')], default='intern', help_text='Wozu der Beschluss gefasst wird; die Wirkungstabelle verzweigt hierüber.', max_length=30),
        ),
        migrations.AlterField(
            model_name='gremienbeschluss',
            name='gremium',
            field=models.CharField(choices=[('expertenrat1', 'Expertenrat — Gruppe 1 (Entwurf)'), ('expertenrat2', 'Expertenrat — Gruppe 2 (Prüfung)'), ('koordinationsrat', 'Koordinationsrat'), ('integritaetsrat', 'Integritätsrat'), ('berichtswesenrat', 'Integrations- und Berichtswesenrat'), ('entwicklungsrat', 'Technischer Entwicklungsrat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rolle',
            name='gremium',
            field=models.CharField(choices=[('expertenrat1', 'Expertenrat — Gruppe 1 (Entwurf)'), ('expertenrat2', 'Expertenrat — Gruppe 2 (Prüfung)'), ('koordinationsrat', 'Koordinationsrat'), ('integritaetsrat', 'Integritätsrat'), ('berichtswesenrat', 'Integrations- und Berichtswesenrat'), ('entwicklungsrat', 'Technischer Entwicklungsrat')], max_length=20),
        ),
        migrations.CreateModel(
            name='Hinweis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quelle', models.CharField(choices=[('parametertest', 'Auswertung eines Parametertests'), ('hervorhebung', 'Kandidat für Hervorhebung'), ('muster', 'Muster-Bericht'), ('last', 'Lastwarnung')], max_length=20)),
                ('titel', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=4000)),
                ('status', models.CharField(choices=[('offen', 'offen'), ('beschluss', 'Beschluss angelegt'), ('verworfen', 'verworfen'), ('kenntnis', 'zur Kenntnis genommen')], default='offen', max_length=12)),
                ('grund', models.CharField(blank=True, max_length=500)),
                ('erledigt_am', models.DateTimeField(blank=True, null=True)),
                ('angelegt_am', models.DateTimeField(default=django.utils.timezone.now)),
                ('antrag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='verfahren.antrag')),
                ('erledigt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hinweis',
                'verbose_name_plural': 'Posteingang',
                'ordering': ['-angelegt_am'],
            },
        ),
    ]
