# Generated by Django 5.2.17 on 2026-09-09 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gremien', '0011_koordinationsrat_werkstatt'),
        ('parameter', '0004_parametertest'),
        ('verfahren', '0015_hilfetexte_ohne_kennungen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hinweis',
            name='parametertest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hinweise', to='parameter.parametertest'),
        ),
        migrations.AddField(
            model_name='interessenbindung',
            name='antrag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interessenbindungen', to='verfahren.antrag'),
        ),
        migrations.AddField(
            model_name='interessenbindung',
            name='mitglied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ueberlastungsmeldung',
            name='antrag_an_mv',
            field=models.ForeignKey(blank=True, help_text='Der Vorschlag als Antrag an die Mitgliederversammlung.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='verfahren.antrag'),
        ),
        migrations.AddField(
            model_name='ueberlastungsmeldung',
            name='beschluss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ueberlastungen', to='gremien.gremienbeschluss'),
        ),
        migrations.AddField(
            model_name='ueberlastungsmeldung',
            name='gemeldet_von',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wunschvermerk',
            name='durch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wunschvermerk',
            name='entwurf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wunschvermerke', to='gremien.entwurf'),
        ),
        migrations.AddField(
            model_name='wunschvermerk',
            name='kommentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='verfahren.kommentar'),
        ),
        migrations.AlterUniqueTogether(
            name='interessenbindung',
            unique_together={('antrag', 'mitglied', 'runde')},
        ),
        migrations.AlterUniqueTogether(
            name='wunschvermerk',
            unique_together={('entwurf', 'kommentar')},
        ),
    ]
