# Generated by Django 5.2.17 on 2026-09-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gremien', '0016_beschluss_fachliste_indizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolle',
            name='ruht_grund',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rolle',
            name='ruht_seit',
            field=models.DateTimeField(blank=True, help_text='Die Rolle ruht (§ 7 Abs 10 lit f letzter Unterabsatz): nach einer verlorenen Vertrauensfrage bis zum Ablauf der Anfechtungsfrist oder zur Entscheidung des Parteischiedsgerichts. Eine ruhende Rolle zählt nicht als aktiv; gelesen wird sie weiter.', null=True),
        ),
        migrations.AlterField(
            model_name='gremienbeschluss',
            name='anlass',
            field=models.CharField(choices=[('intern', 'innere Angelegenheit des Rates'), ('pruefung', 'Prüfung eines Vorschlags (§ 6 Abs 7)'), ('hervorhebung', 'Hervorhebung eines Antrags (§ 5 Abs 10 lit b)'), ('hervorhebung_aufheben', 'Hervorhebung aufheben (§ 5 Abs 10 lit b)'), ('zurueckweisung', 'Zurückweisung eines Antrags (§ 5 Abs 2)'), ('zurueckweisung_aufheben', 'Zurückweisung aufheben (§ 5 Abs 2)'), ('aussetzung', 'Abstimmung oder Vollzug aussetzen (§ 6 Abs 3 lit d)'), ('aussetzung_aufheben', 'Aussetzung aufheben (§ 6 Abs 3 lit d)'), ('regelpruefung', 'Jährliche Prüfung der automatisierten Regeln (§ 2 Abs 6)'), ('einreichung', 'Einreichung eines Vorschlags (§ 5 Abs 12)'), ('austausch', 'Austausch der Gruppe 1 (§ 6 Abs 7)'), ('hervorhebung_anregen', 'Hervorhebung beim Integritätsrat beantragen (§ 5 Abs 10 lit b)'), ('ueberlastung', 'Vorschlag zu einer Überlastungsmeldung (§ 6 Abs 10)'), ('parametertest', 'Test eines Registerwerts anordnen (§ 6 Abs 11 lit c)'), ('parameter_einfuehrung', 'Einführung eines Registerwerts (§ 6 Abs 11 lit c)'), ('vertrauensfrage_sperre', 'Sperre einer Vertrauensfrage feststellen (§ 7 Abs 10 lit g)')], default='intern', help_text='Wozu der Beschluss gefasst wird; die Wirkungstabelle verzweigt hierüber.', max_length=30),
        ),
        migrations.AlterField(
            model_name='hinweis',
            name='quelle',
            field=models.CharField(choices=[('parametertest', 'Auswertung eines Parametertests'), ('hervorhebung', 'Kandidat für Hervorhebung'), ('muster', 'Muster-Bericht'), ('last', 'Lastwarnung'), ('vertrauensfrage', 'Vertrauensfrage (§ 7 Abs 10)')], max_length=20),
        ),
    ]
